# prepare_yolo.py

import os
import shutil
import numpy as np
import pandas as pd
from PIL import Image

import config
from dataset import load_annotations, split_by_image

YOLO_DIR = "yolo_dataset"


def make_dirs():
    for split in ['train', 'val']:
        os.makedirs(os.path.join(YOLO_DIR, 'images', split), exist_ok=True)
        os.makedirs(os.path.join(YOLO_DIR, 'labels', split), exist_ok=True)
    print(f"[prepare_yolo] Created directory structure under {YOLO_DIR}/")


def annotations_to_yolo(group_df, img_w, img_h):
    """
    Standard YOLO format (5 values per line):
        class_id  cx_norm  cy_norm  w_norm  h_norm

    Uses center_x/center_y directly — correct even for rotated boxes.
    bbox_w/h are the screen enclosure dims, good enough for detection.
    """
    lines = []
    for _, row in group_df.iterrows():
        cx_norm = row['center_x'] / img_w
        cy_norm = row['center_y'] / img_h
        w_norm  = row['bbox_w']   / img_w
        h_norm  = row['bbox_h']   / img_h

        cx_norm = max(0.0, min(1.0, cx_norm))
        cy_norm = max(0.0, min(1.0, cy_norm))
        w_norm  = max(0.0, min(1.0, w_norm))
        h_norm  = max(0.0, min(1.0, h_norm))

        lines.append(f"0 {cx_norm:.6f} {cy_norm:.6f} {w_norm:.6f} {h_norm:.6f}")

    return lines


def write_yaml():
    yaml_content = f"""# YOLOv8 dataset config — auto-generated by prepare_yolo.py

path: {os.path.abspath(YOLO_DIR)}

train: images/train
val:   images/val

nc: 1

names:
  0: tube_lid
"""
    yaml_path = os.path.join(YOLO_DIR, 'dataset.yaml')
    with open(yaml_path, 'w') as f:
        f.write(yaml_content)
    print(f"[prepare_yolo] Wrote {yaml_path}")
    return yaml_path


def prepare():
    print("=" * 60)
    print("Preparing YOLO dataset...")
    print("=" * 60)

    make_dirs()

    # Delete old cache files
    for split in ['train', 'val']:
        cache = os.path.join(YOLO_DIR, 'labels', f'{split}.cache')
        if os.path.exists(cache):
            os.remove(cache)
            print(f"[prepare_yolo] Deleted old cache: {cache}")

    df = load_annotations()
    train_df, val_df = split_by_image(df)

    splits = {'train': train_df, 'val': val_df}

    for split_name, split_df in splits.items():
        images_in_split = split_df['image'].unique()
        print(f"\n[prepare_yolo] Processing {split_name}: {len(images_in_split)} images")

        for img_name in images_in_split:
            src_path = os.path.join(config.DATA_DIR, img_name)
            if not os.path.exists(src_path):
                print(f"  WARNING: Image not found: {src_path}")
                continue

            with Image.open(src_path) as img:
                img_w, img_h = img.size

            dst_img_path = os.path.join(YOLO_DIR, 'images', split_name, img_name)
            shutil.copy2(src_path, dst_img_path)

            group = split_df[split_df['image'] == img_name]
            yolo_lines = annotations_to_yolo(group, img_w, img_h)

            label_name = os.path.splitext(img_name)[0] + '.txt'
            label_path = os.path.join(YOLO_DIR, 'labels', split_name, label_name)
            with open(label_path, 'w') as f:
                f.write('\n'.join(yolo_lines))

            print(f"  {img_name} → {len(yolo_lines)} tubes")

    yaml_path = write_yaml()

    print()
    print("=" * 60)
    print("Done! YOLO dataset ready.")
    print(f"  Next step: python detect_train.py")
    print("=" * 60)
    return yaml_path


if __name__ == "__main__":
    prepare()